### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by MrBongoC** [tankarageldi/tankarageldi.github.io#1]
I was checking out the site to make a similar one, noticed these typos:

bussinesses -> businesses
hair style -> hairstyle

😉 🫡

**Comment by tankarageldi** [comment]
Thanks, boss!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tolga Gokturk Cohce ***@***.***>
Sent: Tuesday, September 17, 2024 9:25:25 AM
To: tankarageldi/tankarageldi.github.io ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tankarageldi/tankarageldi.github.io] typos (Issue #1)


I was checking out the site to make a similar one, noticed these typos:

bussinesses -> businesses
hair style -> hairstyle

😉 🫡

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
Fixed @tankarageldi  @Tgcohce
